apiVersion: v1
kind: Service
metadata:
  name: devops-challenge-service
  labels:
    app: devops-challenge
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: devops-challenge